### ISSUE TITLE
throws an error when im trying load the library

### ISSUE THREAD

**Issue by Krendel3** [zig-gamedev/zopengl#1]
symbol to 
export must identify a declaration
    @export(&bindings.cullFace, .{ .name = "glCullFace", .linkage = linkage });

**Comment by hazeycode** [comment]
Hi, I'm not sure why it isn't working for you. Which Zig version are you using and are you able to build and run `minimal_glfw_gl` from the [dev repo](https://github.com/zig-gamedev/zig-gamedev)?

**Comment by Krendel3** [comment]
wasnt working 0.13.0-dev.351+64ef45eb0 got it to work on the newest zig version

**Comment by hazeycode** [comment]
Note that we are tracking Mach nominated Zig version on the main branch atm.

Whatever version a revision is on is written in ./.zigversion

We will also create release packages on each stable zig release hereon.
